from __future__ import annotations

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ErrorResponse(BaseModel):
    code: str
    message: str
    detail: dict[str, Any] = Field(default_factory=dict)


class LoginRequest(BaseModel):
    username: str = Field(min_length=1, max_length=200)
    password: str = Field(min_length=1)


class LoginResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


class ParsedFileOut(BaseModel):
    fileName: str
    fileHash: str
    text: str
    textFormat: Literal["markdown"]
    textLength: int
    reused: bool


class SettingsOut(BaseModel):
    store_raw_text: bool
    notify_on_job_complete: bool
    telemetry_opt_in: bool
    preferred_language: str


class MeOut(BaseModel):
    id: UUID
    email: str | None
    display_name: str | None
    settings: SettingsOut


class MePatch(BaseModel):
    display_name: str | None = None
    settings: dict[str, Any] | None = None


LLMProvider = Literal["auto", "openrouter", "anthropic", "openai_compatible", "fake"]
CustomLLMProvider = Literal["openrouter", "anthropic", "openai_compatible", "fake"]


class LLMSettingsOut(BaseModel):
    source: Literal["environment", "custom"]
    provider: LLMProvider
    base_url: str
    model: str
    temperature: float
    api_key_configured: bool


class LLMSettingsPatch(BaseModel):
    mode: Literal["environment", "custom"]
    provider: CustomLLMProvider | None = None
    base_url: str | None = Field(default=None, max_length=2048)
    model: str | None = Field(default=None, max_length=500)
    temperature: float | None = Field(default=None, ge=0, le=2)
    api_key: str | None = Field(default=None, max_length=10_000, repr=False)
    clear_api_key: bool = False


class WorkflowOut(BaseModel):
    id: str
    name: str
    description: str
    version: str
    domain: str
    task_type: str
    result_type: str
    config_schema: dict[str, Any]
    output_schema: dict[str, Any]
    ui_schema: dict[str, Any]
    ui_config: dict[str, Any]


class JobCreateItem(BaseModel):
    file_name: str = Field(min_length=1, max_length=512, description="Original PDF file name")
    file_hash: str = Field(
        min_length=8,
        max_length=128,
        description="Stable content hash generated by the backend parser",
    )
    text: str = Field(min_length=1, description="Parsed Markdown text; the PDF is not stored")


class JobCreate(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    workflow_id: str = Field(min_length=1, max_length=120)
    config: dict[str, Any] = Field(default_factory=dict)
    items: list[JobCreateItem] = Field(min_length=1, description="Documents in this batch")


class JobCreateOut(BaseModel):
    job_id: UUID
    queued_items: int
    estimated_seconds: int
    reused: bool = False


class JobResumeOut(BaseModel):
    job_id: UUID
    queued_items: int
    unavailable_items: int


class JobOut(BaseModel):
    id: UUID
    workflow_id: str
    workflow_version: str
    config: dict[str, Any]
    status: str
    total_items: int
    completed_items: int
    failed_items: int
    created_at: datetime
    started_at: datetime | None
    finished_at: datetime | None


class JobItemOut(BaseModel):
    id: UUID
    ordinal: int
    file_name: str
    file_hash: str
    text_length: int
    status: str
    parsed_result: dict[str, Any] | None
    error_code: str | None
    error_message: str | None
    duration_ms: int | None
    finished_at: datetime | None


class Property(BaseModel):
    value: str
    unit: str = ""
    remark: str = ""
    source: str = ""
    method: str = ""


class Measurement(BaseModel):
    conditions: dict[str, Property] = Field(default_factory=dict)
    performance: dict[str, Property] = Field(default_factory=dict)
    remark: str = ""
    source: str = ""


class Sample(BaseModel):
    name: str
    properties: dict[str, Property] = Field(default_factory=dict)
    measurements: list[Measurement] = Field(default_factory=list)


class ParsedResult(BaseModel):
    success: bool
    samples: list[Sample] = Field(default_factory=list)
    headers: list[str] = Field(default_factory=list)
    error: str | None = None


class ExtractionResultEnvelope(BaseModel):
    success: bool
    schema_version: str = "1.0"
    workflow_id: str
    workflow_version: str
    result_type: str
    data: dict[str, Any] = Field(default_factory=dict)
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    validation: dict[str, Any] = Field(default_factory=lambda: {"valid": True, "errors": []})
    error: str | None = None


JobStatus = Literal["pending", "running", "completed", "failed", "cancelled"]
